const lang = {
  en: {
    search: "Search",
    GPTSearchPlaceholder: "What would you like to watch today?",
    home: "Home",
    welcome: "Welcome",
    logout: "Logout",
    signIn: "Sign In",
    emailAddress: "Email Address",
    password: "Password",
    newToNetflix: "New to Netflix?",
    signUpNow: "Sign up now",
    signUp: "Sign Up",
    fullName: "Full Name",
    alreadyRegistered: "Already registered?",
    footer: {
      questionsCall: "Questions? Call 000-800-919-1694",
      faq: "FAQ",
      helpCenter: "Help Centre",
      termsOfUse: "Terms of Use",
      privacy: "Privacy",
      cookiePreferences: "Cookie Preferences",
      corporateInformation: "Corporate Information",
    },
    forgotPass:{
      forgot: "Forgot Password?",
      reset: "Reset Password",
      cancel: "Cancel",
      send: "Send Reset Link"
    }
  },
  hi: {
    search: "खोजें",
    GPTSearchPlaceholder: "आप आज क्या देखना चाहेंगे?",
    home: "होम",
    welcome: "स्वागत हैं",
    logout: "लोग आउट",
    signIn: "साइन इन करें",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    newToNetflix: "नेटफ्लिक्स पर नए हैं?",
    signUpNow: "अभी साइन अप करें",
    signUp: "साइन अप करें",
    fullName: "पूरा नाम",
    alreadyRegistered: "पहले से पंजीकृत है?",
    footer: {
      questionsCall: "प्रश्न? कॉल करें 000-800-919-1694",
      faq: "सामान्य प्रश्न",
      helpCenter: "सहायता केंद्र",
      termsOfUse: "उपयोग की शर्तें",
      privacy: "गोपनीयता",
      cookiePreferences: "कुकी पसंद",
      corporateInformation: "कॉर्पोरेट जानकारी",
    },
    forgotPass: {
      forgot: "पासवर्ड भूल गए?",
      reset: "पासवर्ड रीसेट",
      cancel: "रद्द करें",
      send: "रीसेट लिंक भेजें"
    }
  },
  bn: {
    search: "অনুসন্ধান",
    GPTSearchPlaceholder: "আপনি আজ কি দেখতে চান?",
    home: "হোম",
    welcome: "স্বাগতম",
    logout: "লগ আউট",
    signIn: "সাইন ইন করুন",
    emailAddress: "ইমেইল ঠিকানা",
    password: "পাসওয়ার্ড",
    newToNetflix: "নেটফ্লিক্সে নতুন?",
    signUpNow: "এখন সাইন আপ করুন",
    signUp: "সাইন আপ করুন",
    fullName: "পুরো নাম",
    alreadyRegistered: "ইতিমধ্যে নিবন্ধিত?",
    footer: {
      questionsCall: "প্রশ্ন? কল করুন 000-800-919-1694",
      faq: "সাধারিত প্রশ্ন",
      helpCenter: "সাহায্য কেন্দ্র",
      termsOfUse: "ব্যবহারের শর্তাবলী",
      privacy: "গোপনীয়তা",
      cookiePreferences: "কুকি পছন্দ",
      corporateInformation: "কর্পোরেট তথ্য",
    },
    forgotPass: {
      forgot: "পাসওয়ার্ড ভুলে গেছেন?",
      reset: "পাসওয়ার্ড রিসেট",
      cancel: "বাতিল করুন",
      send: "রিসেট লিঙ্ক প্রেরণ করুন"
    }
  },
  mr: {
    search: "शोध",
    GPTSearchPlaceholder: "आपण आज काही पाहायचं आहे का?",
    home: "होम",
    welcome: "स्वागत आहे",
    logout: "बाहेर पडणे",
    signIn: "साइन इन करा",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    newToNetflix: "नेटफ्लिक्सला नवीन?",
    signUpNow: "आता साइन अप्प करा",
    signUp: "साइन अप्प करा",
    fullName: "पूर्ण नाव",
    alreadyRegistered: "आधीच नोंदवलेले?",
    footer: {
      questionsCall: "सवाले? 000-800-919-1694 वर कॉल करा",
      faq: "अक्सर पूँछणारे प्रश्न",
      helpCenter: "सहाय्य केंद्र",
      termsOfUse: "वापराच्या अटी",
      privacy: "गोपनीयता",
      cookiePreferences: "कुकी पसंती",
      corporateInformation: "कॉर्पोरेट माहिती",
    },
    forgotPass: {
      forgot: "पासवर्ड विसरलात?",
      reset: "पासवर्ड रीसेट",
      cancel: "रद्द करा",
      send: "रीसेट लिंक पाठवा"
    }
  },
  te: {
    search: "వెతకండి",
    GPTSearchPlaceholder: "మీరు ఈ రోజు ఏమి చూడాలి?",
    home: "హోమ్",
    welcome: "స్వాగతం",
    logout: "లాగ్ అవుట్",
    signIn: "సైన్ ఇన్ చేయండి",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    newToNetflix: "నెట్‌ఫ్లిక్స్‌కు కొత్తగా?",
    signUpNow: "ఇప్పుడే సైన్ అప్ చేయండి",
    signUp: "సైన్ అప్ చేయండి",
    fullName: "పూర్తి పేరు",
    alreadyRegistered: "ఇప్పటికే నమోదైనదా?",
    footer: {
      questionsCall: "ప్రశ్నలు? 000-800-919-1694 కాల్ చేయండి",
      faq: "అక్కడా అడిగే ప్రశ్నలు",
      helpCenter: "సహాయ కేంద్రం",
      termsOfUse: "ఉపయోగ షరతులు",
      privacy: "గోప్యత",
      cookiePreferences: "కుకీ అభిరుచులు",
      corporateInformation: "కార్పొరేట్ సమాచారం",
    },
    forgotPass: {
      forgot: "పాస్‌వర్డ్‌ను మర్చిపోయారా?",
      reset: "పాస్‌వర్డ్‌ను రీసెట్ చేయండి",
      cancel: "రద్దు చేయండి",
      send: "రీసెట్ లింక్ పంపండి"
    }
  },
  ta: {
    search: "தேடு",
    GPTSearchPlaceholder: "நீங்கள் இன்று என்னைப் பார்க்க விரும்புகிறீர்களா?",
    home: "ஹோம்",
    welcome: "வரவேற்கின்றோம்",
    logout: "வெளியேறு",
    signIn: "உள்நுழைய",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    newToNetflix: "நெட்ஃபிளிக்ஸில் புதியவரா?",
    signUpNow: "இப்போது பதிவு செய்க",
    signUp: "பதிவு செய்ய",
    fullName: "முழு பெயர்",
    alreadyRegistered: "ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது?",
    footer: {
      questionsCall: "கேள்விகள்? 000-800-919-1694 ஐ அழையவும்",
      faq: "அனைத்துக்கும் கேட்கைகள்",
      helpCenter: "உதவி மையம்",
      termsOfUse: "பயன்பாட்டு விதிமுறைகள்",
      privacy: "தனியுரிமை",
      cookiePreferences: "குக்கீ விருதுகள்",
      corporateInformation: "கார்ப்பரேட் தகவல்",
    },
    forgotPass: {
      forgot: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
      reset: "கடவுச்சொல் மீளமைக்க",
      cancel: "ரத்து செய்",
      send: "மீள்மூலம் இணைப்பு அனுப்பு"
    },
  },
};

export default lang;
